# Site settings
title: appserver.io
email: info@appserver.io
description: > # The objective of the project is to develop a multithreaded
  application server for PHP, written in PHP. Yes, pure PHP! You think we
  aren't serious? Maybe! But we think, in order to enable as many developers
  in our great community, this will be the one and only way. So with your
  help we hopefully establish a solution as the standard for enterprise
  applications in PHP environments.

timezone: Europe/Berlin
future: false
port: 4000
host: 0.0.0.0
baseurl: ""
url: "http://appserver.io"

collections:
  redirects:
    output: true
  docs:
    output: true
  faq:
    output: true
  tuts:
    output: true
  features:
    path: products/

twitter_username: php_appserver

github_username:  appserver-io
github_repository: https://github.com/appserver.io/appserver
github_issue: https://github.com/appserver-io/appserver/issues/

google_analytics_id: UA-42386171-1

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
